version: "3.8"
services:
  book-management-backend:
    image: nodejs_mongo_docker
    build: .
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - book-management-backend:/data/db
volumes:
  book-management-backend:
